### ISSUE TITLE
Intermittent network error

### ISSUE THREAD

**Issue by krose422** [iaphub/react-native-iaphub#106]
I am intermittently getting `network_error` when requesting `getProductsForSale` and `getActiveProducts`. After creating new products yesterday and publishing a new listing, I successfully fetched products. I also successfully tested a purchase in the sandbox environment. Nothing has changed with my app setup, but I am now receiving a network error. Any help would be greatly appreciated; thank you!

**Comment by iaphub** [comment]
Hi @krose422.
Are you sure you do not have any connectivity issues?
Could you check `err.params`, it should contain two properties `response` and `status` in order to get more information about while your request is failing.
Please contact `support@iaphub.com` with your app ID and the err params and our team will try to help you.
