### ISSUE TITLE
Different Users Subscriptions issue

### ISSUE THREAD

**Issue by WtfLaika** [iaphub/react-native-iaphub#108]
**Current behavior**

Buy subscription using the first account, unsubscribe and log out. Then log in  to another account,subscribe and you'll get error and first account will be subscribed

**Expected behavior**

Second account will be either subscribed or will get error without payment.

**Platform**

 iOS

**Environment**
"react-native": "0.64.1"
 "react-native-iap": "5.2.6",
 "react-native-iaphub": "6.4.1",

**Comment by WtfLaika** [comment]
> 



> Hi @WtfLaika, It is totally normal, if you're looking to transfer the subscription to the second account you'll have to restore the in-app purchases (Iaphub.restore() method: https://github.com/iaphub/react-native-iaphub#restore-user-purchases)

Hi @iaphub!

But I don't want  to transfer or restore  subscription.

There should be absolutely separated subscriptions for all users, a certain user has it’s own subscription. When we have another user(account) it has another subscription. 

For example look on logic of subscriptions Duolingo.

**Comment by iaphub** [comment]
That's how iTunes/GooglePlay is working, you cannot have the same subscription twice with the same GooglePlay/iTunes account.

**Comment by rumbaa01** [comment]
Hello @iaphub @WtfLaika , 

I have the same issue as @WtfLaika  described. 

Let me describe the conditions first: 

**Data:** 
Platform - IOS
Apple Id account - the same 1 account
1st user account inside the app - A
2nd user account inside the app - B

**Steps:** 
1. Buy a subscription to A account
2. Unsubscribe A account
3. Try to buy a subscription to B account

**Actual behavior:**
Code works as expected per your documentation. It will throw the next error - "user conflict".
<img width="840" alt="image" src="https://user-images.githubusercontent.com/15148689/161263216-d94f2563-3ac4-435d-a80f-8268febfabde.png">

**Expected behavior:**
1. Don't make the transaction
2. Get only error

**The main question is:** 
Is it possible to not buy a product if the product belongs to a different user? Bc, it confuses me a lot as a user.
