### ISSUE TITLE
'Reciept failed'

### ISSUE THREAD

**Issue by ciawalsh** [iaphub/react-native-iaphub#12]
I am moving over from react-native-iap to react-native-iaphub (due to the hub having inbuilt webhooks for subscription changes), however during development on my staging environment, I am constantly getting 'the processing of a receipt has failed' notification emails.

I have setup that the `Iaphub` is initialised at the correct place on app startup, I then login in a user at the correct stage too - I can get a list of `productsForSale` where I need to, so that's working fine.

However, it's when I use the `Iaphub.buy(productSku)` I have issues. It's for both consumables and renewable subscriptions. I have setup the shared secret for iOS and the Google Play credentials for Android, so the processing should go through fine... As I said at the beginning, I am moving over from react-native-iap, and the purchases/subscriptions worked fine there - and I believe you use this package anyway as a dependency for `iaphub`.

I tried adding my card to move to a 'production plan` in case it was that however, that hail mary didn't work.

Am I missing something?

**Comment by iaphub** [comment]
Hi @ciawalsh,
I'm looking at your app.
On the 'Receipts' page you can see a detailed report of your receipts and it looks like your ios receipts can't process because itunes is returning that your shared secret is invalid.
If you're still having issues after updating your shared secret, please contact directly the support on the chat available on the website (button on the bottom right).

Thanks

**Comment by Shahrukh0396** [comment]
getting same issue.
