### ISSUE TITLE
How do I handle promoted products in iOS?

### ISSUE THREAD

**Issue by kurniawanw0194** [iaphub/react-native-iaphub#13]
At the moment, this library does not support promoted products in iOS. Is this feature planned in future builds?

**Comment by iaphub** [comment]
Correct, the feature is on the roadmap indeed it'll be available soon.
In the meantime, since the library is based on react-native-iap which support promoted products you can already implement it with some extra code.

Here is the code from the [react-native-iap](https://github.com/dooboolab/react-native-iap) documentation:
```js
import { NativeModules, NativeEventEmitter } from 'react-native'
const { RNIapIos } = NativeModules;
const IAPEmitter = new NativeEventEmitter(RNIapIos);

IAPEmitter.addListener('iap-promoted-product', async () => {
  const productId = await RNIap.getPromotedProductIOS();

  if (productId !== null) {
    try {
      await RNIap.buyPromotedProductIOS();
    } catch(error) {
      console.warn(error);
    }
  }
});
```

**Comment by iaphub** [comment]
I'm closing the issue but if you have any other question do not hesitate 👍
