### ISSUE TITLE
Unable to get the user when a product sku is not found

### ISSUE THREAD

**Issue by David6Mat** [iaphub/react-native-iaphub#16]
Hi,

I try to use the "getUser()" method of the plugin.
Except that if a product was not found in the platform in question, I never recovers the user with the rest of the products available ...

Tanks.

**Comment by iaphub** [comment]
Hi,

When a product is not found we are showing an error modal (using console.error), this modal won't be displayed if you compile the app in production.
And the list of the products is still returned (except the product that isn't found).
If you want to remove the product that doesn't exist you can remove it from your listing you created on IAPHUB and the error should disappear.

**Comment by centrual** [comment]
Hello,

It's happening to me too. Everything working for android but on ios "product not found" error happening. I tested this situation for development mode also production mode. Because of this error, the app store rejecting our application.

I checked API endpoint for ios, it's returning products. Also, I double-checked the product SKUs from the app store connect. Also, I added in-app products to release.

![image](https://user-images.githubusercontent.com/2001424/86593821-a27c1400-bf9e-11ea-8f9a-b4dc9a43dca2.png)

![WhatsApp Image 2020-07-06 at 15 41 03](https://user-images.githubusercontent.com/2001424/86594138-2a621e00-bf9f-11ea-9157-77d80db8be60.jpeg)

![Başlıksız-1](https://user-images.githubusercontent.com/2001424/86594645-15d25580-bfa0-11ea-9a13-1bdd9b1c1675.png)

![image](https://user-images.githubusercontent.com/2001424/86594940-95602480-bfa0-11ea-9afe-c6e098207502.png)

![image](https://user-images.githubusercontent.com/2001424/86594958-a27d1380-bfa0-11ea-8d3c-874f7fd250d8.png)

![image](https://user-images.githubusercontent.com/2001424/86594989-b0329900-bfa0-11ea-9a95-b5735cf0d5f8.png)

![image](https://user-images.githubusercontent.com/2001424/86595028-c6405980-bfa0-11ea-8797-25aa594e7d89.png)

![Başlıksız-2](https://user-images.githubusercontent.com/2001424/86595186-04d61400-bfa1-11ea-97cd-4ab77c1cfb18.png)

![WhatsApp Image 2020-07-06 at 15 56 19](https://user-images.githubusercontent.com/2001424/86595584-99d90d00-bfa1-11ea-8acb-66c4fe39ca41.png)

**Comment by iaphub** [comment]
We've been in contact by email with @centrual, the issue ended up having the wrong product type (non-renewable subscriptions instead of renewable subscriptions).
Closing the issue.
