### ISSUE TITLE
8 arguments expected in buyItemByType

### ISSUE THREAD

**Issue by deggertsen** [iaphub/react-native-iaphub#35]
Just tried to update to the most recent version 5.1.0 (along with the recommended react native iap V4.6.3) and I'm getting this error. I don't have a lot more information that I'm sure would be helpful, but hopefully this report helps in some way.

> RNIapModule.buyItemByType got 7 arguments, expected 8

**Comment by iaphub** [comment]
Hi @deggertsen,

I think you might have some conflict in your dependencies since the buyItemByType method of the version 4.6.3 doesn't have 8 parameters:
https://github.com/dooboolab/react-native-iap/blob/c25d6e60dfeed472be39266efb7acd599c8c6090/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java#L416

Can you try removing your node_modules folder and install again?

**Comment by deggertsen** [comment]
I tried removing all my node_modules folder and installed again multiple times with the same result. For now we're done with this native release and will stick with V4.1.3. We'll try again next time we are running a native release.

**Comment by iaphub** [comment]
Ok that's weird, you could double check directly in node_modules/react-native-iap that you're having the correct version.
Also maybe `cd android &&./gradlew clean` could help.
Closing this issue, contact me by email if you're still having the issue when you try again next time.
