### ISSUE TITLE
Is sandbox environnement mandatory to call getProductsForSale() ?

### ISSUE THREAD

**Issue by ingerable** [iaphub/react-native-iaphub#47]
I'm currently having an error product sku not found. Is it possible to call IAPhub api without being on an internal test apk with the sandbox environnement ? We are not in testing phase but in developpement phase.

**Comment by iaphub** [comment]
This error is related to GooglePlay not IAPHUB, it means GooglePlay isn't returning your products because something isn't configured correctly.
Uploading an APK to a closed track is only required to enable the In-app-purchases with GooglePlay, you should be able after that to load your in-app products in development.
