### ISSUE TITLE
[question] how can i get Detect and process invalidated purchases

### ISSUE THREAD

**Issue by gruming** [iaphub/react-native-iaphub#6]
hello,

How can i get Detect and process invalidated purchases for android and ios ? 
[[ref From Google Document]](https://developer.android.com/google/play/billing/security)

i saw webhook types from documentation

purchase
refund 
subscription_renewal 
subscription_replace 
subscription_cancel 
subscription_expire

but not found Detect and process invalidated purchases

any idea ??

**Comment by iaphub** [comment]
Hi @gruming,

When a receipt is invalid because of fraud or anything else, IAPHUB will sent you an email with the link to the receipt page with a detailed report of the issues. (You can access to the receipt page directly from the dashboard as well).
Please note that no purchase will be processed if the receipt is invalid.

Does it answer your question?
