### ISSUE TITLE
[Question]: Regarding new payment system

### ISSUE THREAD

**Issue by myckhel** [iaphub/react-native-iaphub#78]
I would like to know if account with 0 revenue is fair enough to be charged $27 monthly?

Some projects might be on their early release face and might barely have active users 200.
it could take some projects to start generating revenues after some months but with this new pricing system they are likely to pay more than what they earn.

maybe percentage based charges will favour most projects.

**Comment by iaphub** [comment]
Hi @myckhel,

This is why we're starting with a very small fee of $29.
Most services (Cloud hosting, Software...) do not take into account the revenue of their users, we're taking that into account in order to help but we're aware there is no perfect system for everyone.

If you have more questions you can contact us at `support@iaphub.com`, we're trying to use Github issues for questions related to the plugin.
