### ISSUE TITLE
GooglePlay did not return the product

### ISSUE THREAD

**Issue by Oriole-Alex** [iaphub/react-native-iaphub#86]
Hi, I am unable to get any products to show up. I have created them on the Google Play store, it's been longer than 36 hours since I created them - all I get on my app when I call getProductsForSale is the following error:

GooglePlay did not return the product 'artist', the product has been filtered, if the sku is valid your GooglePlay account or sandbox environment is probably not configured properly (https://iaphub.com/docs/set-up-android/configure-sandbox-testing)
GooglePlay did not return the product 'curator', the product has been filtered, if the sku is valid your GooglePlay account or sandbox environment is probably not configured properly (https://iaphub.com/docs/set-up-android/configure-sandbox-testing)
GooglePlay did not return the product 'art_lover', the product has been filtered, if the sku is valid your GooglePlay account or sandbox environment is probably not configured properly (https://iaphub.com/docs/set-up-android/configure-sandbox-testing)

Any help would be fantastic
Thanks a mil

**Comment by iaphub** [comment]
Hi @Oriole-Alex,

The issue is that Google Play isn't returning your products, something must be incomplete.
Double check all the steps listed on the page (https://iaphub.com/docs/set-up-android/configure-sandbox-testing):
- You have to add your google account in license testing (and your phone must be connected to the account)
- You have to upload your app to a closed track (double check your bundle id is correct as well)
- You have to create a list of testers and click on the link to join the test
- You have to use a real device

PS: The screenshots on the page are outdated (we'll update them asap) but it's working the same.
