### ISSUE TITLE
Unable to get subscriptions unless calling .restore() which is very slow

### ISSUE THREAD

**Issue by petter-kaspersen** [iaphub/react-native-iaphub#92]
Facing a little issue where I am unable to fetch active subscriptions unless I call `restore()` before doing so.

The restore call is very slow, and fills the screen with a white loading screen, that on TestFlight lasts for about 5-10 seconds. Is there any way around this?

Version of react-native-iaphub: 6.2.2

**Comment by iaphub** [comment]
Hi @petter-kaspersen,

Does it happen right after purchasing the subscription? If a restore is needed it's probably because the subscription is owned by a different user id and during the restore the subscription is migrated to the current user id.
Regarding the restore it's quite slow in testing because your user probably has a ton of test purchases, it's likely going to be faster in production.
You can contact us at `support@iaphub.com` and provide your app id, we'll be able to investigate your issue a little further.
