### ISSUE TITLE
Can we get products for sale without filtering out already bought products? Needed particularly in sandbox

### ISSUE THREAD

**Issue by awadesmoline** [iaphub/react-native-iaphub#96]
Alternative question: How do I make an already bought non-consumable product to show up for user to buy again in sandbox. Subscriptions expire within minutes, I'd like to something like that for non-consumable.

**Comment by iaphub** [comment]
Hi @awadesmoline,
non-consumble are unfortunately pretty difficult to test unfortunately, in order to buy a non-consumable again you'll have to create a new itunes sandbox account.
If you need to do a lot of testing to test webhooks etc.. I would recommend create a consumable for testing since you can purchase as any consumable as you want.

**Comment by awadesmoline** [comment]
Okay. Thanks!
